SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
       TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
       UI.GENDER AS GENDER,
       COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
INNER JOIN USER_INFO UI ON UI.USER_ID = OS.USER_ID
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')), UI.GENDER
HAVING UI.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER
