SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * b.amount) AS TOTAL_SALES
FROM FOOD_PRODUCT a 
JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE TO_CHAR(b.PRODUCE_DATE, 'YYMM') = '2205' 
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC
