--리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD')
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID	
WHERE M.MEMBER_ID = (SELECT MEMBER_ID
                     FROM REST_REVIEW
                     GROUP BY MEMBER_ID
                     ORDER BY COUNT(MEMBER_ID) DESC
                     FETCH FIRST 1 ROW ONLY)
ORDER BY TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') ASC, R.REVIEW_TEXT ASC