SELECT DISTINCT a.FLAVOR
FROM FIRST_HALF a
JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER >= 3000 AND b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY (SELECT TOTAL_ORDER FROM FIRST_HALF WHERE FLAVOR = a.FLAVOR) DESC
