SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE STATUS WHEN 'DONE' THEN '거래완료'
            WHEN 'RESERVED' THEN '예약중'
            WHEN 'SALE' THEN '판매중'
            ELSE STATUS
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYMMDD') = '221005'
ORDER BY BOARD_ID DESC